### ISSUE TITLE
BETS sem conexão

### ISSUE THREAD

**Issue by analisemacro** [nmecsys/BETS#2]
Olá pessoal, tudo bem?

Estamos tentando baixar séries com o BETS, mas ele está dando problema. Vem a mensagem:

ipca = BETS.get(433)
You want to install a development version of RMySQL and DBI package packages?
(This may solve the connection problem)[Y/n]

Tentamos baixar as versões mais novas desses pacotes, mas não resolveu.

Se puderem verificar, ajudará bastante! 

Abs

**Comment by GreedBlink** [comment]
Problemas com o servidor do BETS, já corrigido!

**Comment by rogeriocb2** [comment]
Aparece a mesma mensagem quando chamo a função BETS.get

**Comment by rogeriocb2** [comment]
O problema continua, poderiam ajudar?

**Comment by talithafs** [comment]
@GreedBlink vou reabrir essa issue. Tem alguma coisa muito estranha acontecendo com o servidor, ainda. Pode verificar?

**Comment by GreedBlink** [comment]
A correção foi imediatamente feita na versão do pacote do github! 

```
install.packages("devtools")
require(devtools)
install_github("nmecsys/BETS")
require(BETS)

ipca = BETS.get(433)
```
