### ISSUE TITLE
Argumento data.frame na função BETS.get não está funcionando 

### ISSUE THREAD

**Issue by daianemarcolino** [nmecsys/BETS#3]
BETS.get(433, data.frame = F) e BETS.get(433, data.frame = T) estão retornando a mesma coisa: um data.frame

**Comment by talithafs** [comment]
Tem alguma coisa errada com o servidor. Já tinham me falado isso. Parece que o pacote não olha mais a tabela de metadados pra encontrar a periodicidade da série e, então, montar o objeto ts. @GreedBlink , o que pode estar acontecendo com o servidor? Temos que ver isso rápido, porque o fato de retornar ts é uma grande mão na roda pros nossos usuários.

**Comment by GreedBlink** [comment]
Vou checar, mas deve ser isso mesmo. A estrutura verifica a periodicidade da série antes de fazer o resquest no banco central. O problema deve estar ai, vou corrigir e submeter a nova versão ao CRAN.

**Comment by GreedBlink** [comment]
Resolvido! :+1:

**Comment by daianemarcolino** [comment]
obrigada!!! sucesso!
