### ISSUE TITLE
BETS não funciona

### ISSUE THREAD

**Issue by analisemacro** [nmecsys/BETS#4]
Olá, pessoal, o BETS parece que parou novamente...

ipca = BETS.get(433)
You want to install a development version of RMySQL and DBI package packages?
(This may solve the connection problem)[Y/n]n
Error in value[[3L]](cond) : Connetcion fail!

**Comment by talithafs** [comment]
@analisemacro a FGV migrou nosso servidor e estamos enfrentando problemas com ele. Pensávamos que já estava tudo resolvido, mas ainda não. Já retornamos.

@GreedBlink pode ver isso?

**Comment by GreedBlink** [comment]
A versão de desenvolvimento está atualizada com a correção do problema!

**Comment by analisemacro** [comment]
Instalei aqui a versão do github e o problema continua...

ipca = BETS.get(433)
You want to install a development version of RMySQL and DBI package packages?
(This may solve the connection problem)[Y/n]

Alguma sugestão? :(

**Comment by GreedBlink** [comment]
Estranho, mas vamos verificar! 

A versão 0.3.6 já está no CRAN. Remova a versão que está instalada em seu ambiente e instale a versão completa CRAN.

Por favor, nos informe se deu certo!
