### ISSUE TITLE
Pacote BETS

### ISSUE THREAD

**Issue by rogeriocb2** [nmecsys/BETS#5]
Olá, alguém pode me ajudar, estou querendo reproduzir os exemplos do site: https://cran.r-project.org/web/packages/BETS/vignettes/BETS_basic_usage.html
Aparece a seguinte mensagem de problema de conexão:

You want to install a development version of RMySQL and DBI package packages?
(This may solve the connection problem)[Y/n]

**Comment by talithafs** [comment]
Vamos verificar, @rogeriocb2. Estamos tendo problemas com o nosso servidor : (

**Comment by GreedBlink** [comment]
Problema com a conexão no nosso servidor!

@rogeriocb2 , você pode reproduzir os exemplos do vignettes do BETS usando a versão de desenvolvedor do pacote. Instale utilizando os seguintes códigos: 

`install.packages("devtools")
require(devtools)
install_github("nmecsys/BETS")
require(BETS)
`
A atualização com as correções está sendo finalizada e será encaminhada ao CRAN ainda hoje! 

Obrigado pelo report!
