### ISSUE TITLE
key.rds

### ISSUE THREAD

**Issue by vzendron** [nmecsys/BETS#7]
Pessoal, estou tendo o seguinte erro:

*Error in gzfile(file, "rb") : não é possível abrir a conexão
Além disso: Warning message:
In gzfile(file, "rb") :
  não foi possível abrir o arquivo comprimido '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/BETS/data/key.rds', motivo provável 'No such file or directory'*

Alguma ajuda?
Obrigado.

**Comment by GreedBlink** [comment]
Olá @vzendron, acabamos de atualizar o pacote. Por favor, reinstale o pacote e tente usar a `BETSget` ou `BETSsearch` novamente.

**Comment by vzendron** [comment]
Agora funcionou!

**Comment by GreedBlink** [comment]
@vzendron , obrigado pelo feedback!
